import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { CalculationResult } from "@/lib/tools/types";

interface jsPDFWithAutoTable extends jsPDF {
  lastAutoTable: { finalY: number };
}

export function generatePdf(result: CalculationResult, toolName: string): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(20);
  doc.text(toolName, pageWidth / 2, 20, { align: "center" });

  doc.setFontSize(10);
  doc.text(`Generated by FinScope — ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: "center" });

  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.5);
  doc.line(14, 32, pageWidth - 14, 32);

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  const summaryLines = doc.splitTextToSize(result.summary, pageWidth - 28);
  doc.text(summaryLines, 14, 42);

  let yPos = 42 + summaryLines.length * 5 + 8;

  if (result.warnings.length > 0) {
    doc.setTextColor(239, 68, 68);
    doc.setFontSize(11);
    doc.text("Warnings:", 14, yPos);
    yPos += 6;
    doc.setFontSize(9);
    for (const w of result.warnings) {
      const lines = doc.splitTextToSize(`- ${w}`, pageWidth - 28);
      doc.text(lines, 14, yPos);
      yPos += lines.length * 4 + 2;
    }
    yPos += 4;
  }

  doc.setTextColor(0, 0, 0);

  if (result.metrics.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.text("Key Metrics", 14, yPos);
    yPos += 6;

    const metricsRows = result.metrics.map((m) => [m.label, m.value, m.change || "-"]);
    autoTable(doc, {
      startY: yPos,
      head: [["Metric", "Value", "Change"]],
      body: metricsRows,
      theme: "striped",
      headStyles: { fillColor: [99, 102, 241] },
    });
    const metricTable = doc as unknown as jsPDFWithAutoTable;
    yPos = metricTable.lastAutoTable.finalY + 10;
  }

  for (const section of result.sections) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.text(section.title, 14, yPos);
    yPos += 6;

    if (section.type === "table" && section.headers && section.rows) {
      autoTable(doc, {
        startY: yPos,
        head: [section.headers],
        body: section.rows,
        theme: "striped",
        headStyles: { fillColor: [99, 102, 241] },
      });
      const sectionTable = doc as unknown as jsPDFWithAutoTable;
      yPos = sectionTable.lastAutoTable.finalY + 10;
    } else if (section.type === "text" && section.content) {
      doc.setFontSize(10);
      const lines = doc.splitTextToSize(section.content, pageWidth - 28);
      doc.text(lines, 14, yPos);
      yPos += lines.length * 4 + 10;
    }
  }

  if (result.recommendations.length > 0) {
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(14);
    doc.text("Recommendations", 14, yPos);
    yPos += 6;

    for (const rec of result.recommendations) {
      doc.setFontSize(11);
      if (rec.priority === "high") {
        doc.setTextColor(239, 68, 68);
      } else if (rec.priority === "medium") {
        doc.setTextColor(245, 158, 11);
      } else {
        doc.setTextColor(99, 102, 241);
      }
      doc.text(`${rec.priority.toUpperCase()}: ${rec.title}`, 14, yPos);
      yPos += 5;
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      const lines = doc.splitTextToSize(rec.description, pageWidth - 28);
      doc.text(lines, 14, yPos);
      yPos += lines.length * 4 + 2;
      if (rec.impact) {
        doc.setTextColor(16, 185, 129);
        doc.text(`Impact: ${rec.impact}`, 14, yPos);
        yPos += 4;
      }
      yPos += 4;
      doc.setTextColor(0, 0, 0);

      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
    }
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Powered by FinScope — Smart Finance Planner", pageWidth / 2, 288, { align: "center" });

  return doc;
}
